version: '3.8'

services:
  tape-calculator-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tape-calculator-web
    ports:
      - "8080:80"
    restart: unless-stopped
